# Generated by Django 3.2.14 on 2022-07-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='タスク名', max_length=100)),
                ('description', models.TextField(help_text='備考欄')),
                ('task_status', models.CharField(choices=[('', 'Select'), ('Not implemented', 'Not implemented'), ('In progress', 'In progress'), ('Pending', 'Pending'), ('Closed', 'Closed')], help_text='ステータス', max_length=20)),
                ('limit_time', models.DateTimeField(help_text='期限')),
                ('created_at', models.DateTimeField(help_text='作成日時')),
                ('update_at', models.DateTimeField(help_text='更新日時')),
            ],
        ),
    ]
