# Generated by Django 3.2.14 on 2022-07-18 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='タスク名', max_length=100)),
                ('description', models.TextField(help_text='備考欄')),
                ('task_status', models.CharField(choices=[('', 'Select'), ('Not implemented', 'Not implemented'), ('In progress', 'In progress'), ('Pending', 'Pending'), ('Closed', 'Closed')], help_text='ステータス', max_length=20)),
                ('limit_time', models.DateTimeField(help_text='期限')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
